.gitignore
docker-compose.yml

Task: 공통 패키지 구조용 .gitkeep 파일 추가

---

.gitignore
src/main/java/com/team01/hrbank/entity/BaseEntity.java
src/main/java/com/team01/hrbank/entity/BaseUpdatableEntity.java

Closes #이슈번호
---
- 부서 등록 API 구현
- 컨트롤러, 서비스, DTO 작성
---
- Department 엔티티 생성
- POST /departments API 구현
- 유효성 검사 로직 추가 (부서명 중복 금지)
- 단위 테스트 코드 작성

공용 Entity 설정

---

src/main/java/com/team01/hrbank/entity/BaseEntity.java
src/main/java/com/team01/hrbank/entity/Department.java
src/main/java/com/team01/hrbank/repository/DepartmentRepository.java

Closes #17 
---
- Department 엔티티 클래스 생성
- DepartmentRepository 인터페이스 생성
---
- 필드: id, name, description, establishedDate
- name 필드에 unique 제약 설정
- 유효성 검사 로직 추가 (부서명 중복 금지)
- JpaRepository 상속으로 기본 CRUD 구현

[안재관 | 0422] Feature/13 Department 엔티티 및 레포지토리 생성

---

src/main/java/com/team01/hrbank/dto/department/DepartmentCreateRequest.java
src/main/java/com/team01/hrbank/dto/department/DepartmentDto.java
src/main/java/com/team01/hrbank/mapper/DepartmentMapper.java

Closes #18 
---
- 부서 등록 요청 DTO를 설계하고, 엔티티와 매핑하기 위한 MapStruct 매퍼 작성
---
- DepartmentCreateRequest DTO 클래스 생성
- DepartmentDto 응답 DTO 정의
- DepartmentMapper 인터페이스 작성 (MapStruct 사용)

[안재관 | 0422] Feature/18 Department DTO 및 Mapper 설계

---

src/main/java/com/team01/hrbank/entity/BaseEntity.java
src/main/java/com/team01/hrbank/entity/BaseUpdatableEntity.java
src/main/java/com/team01/hrbank/entity/BinaryContent.java

Closes #24
---
-  프로필 저장에 필요한 바이너리 콘텐트 엔티티 생성
---
- 바이너리 콘텐트 엔티티 생성

[양찬혁|0422] (파일관리) 바이너리콘텐트 엔티티 생성

---

src/main/java/com/team01/hrbank/entity/BinaryContent.java
src/main/java/com/team01/hrbank/service/DepartmentService.java
src/main/java/com/team01/hrbank/service/DepartmentServiceImpl.java

Closes #19 
---
- 부서 등록 비즈니스 로직을 구현, 이름 중복 검사 기능을 포함한 서비스 계층을 완성
---
- DepartmentService 인터페이스 및 구현체 생성
- registerDepartment 메서드 구현
- 중복 이름 검사 → 예외 처리
- DTO → Entity 변환 및 저장 처리

[안재관 | 0422] Feature/19 부서 등록 서비스 로직 및 중복 검사 구현

---

src/main/java/com/team01/hrbank/constraint/EmployeeStatus.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/repository/EmployeeStatusRepository.java

Closes #이슈번호
Closes #22
---
- 직원 엔티티 구현
- 직원 jpa 레포지토리 구현
---
- 직원 엔티티 매핑 관계 구현
- 직원 레포지토리 인터페이스 구현

[한성태 | 0422] Feature/22 직원 등록 엔티티 및 레포지토리 구현

---

src/main/java/com/team01/hrbank/controller/DepartmentController.java
src/main/java/com/team01/hrbank/exception/DuplicateDepartmentNameException.java
src/main/java/com/team01/hrbank/exception/ErrorResponse.java
src/main/java/com/team01/hrbank/exception/GlobalExceptionHandler.java
src/main/java/com/team01/hrbank/service/DepartmentServiceImpl.java

Closes #20 
---
- 부서 등록 API 엔드포인트를 작성하고, 발생 가능한 예외 처리 로직을 구성
---
- POST /api/departments 컨트롤러 메서드 작성
- 요청 DTO → 서비스 호출 → 응답 반환 구조 설계
- 중복 이름 예외 및 유효성 검증 실패 예외 처리
- 커스텀 예외 및 에러 메시지 작성 (전역 예외 처리기 활용)

[안재관 | 0422] Feature/20 부서 등록 API 및 예외 처리 로직 구현

---

src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeDto.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/mapper/EmployeeMapper.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/repository/EmployeeStatusRepository.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/EmployeeServiceImpl.java

Closes #23 
---
- Service SaveMethod 구현
- 응답객체 및 맵퍼 컴포넌트 구현
---
- Service SaveMethod 구현(필요한 객체가 아직 완성되지 않아 추후 수정 필요)
- Employee mapper component 구현
- CreateEmployeeRequest Class 구현
- EmployeeDto.class 구현
- EmployeeRepository email 데이터 검증 메서드 추가

[한성태 | 0422] Feature/23 직원 등록 서비스 로직 및 맵퍼 컴포넌트 응답 객체 구현

---

src/main/java/com/team01/hrbank/repository/binarycontent/BinaryContentRepository.java
src/main/java/com/team01/hrbank/repository/binarycontentstorage/BinaryContentStorage.java
src/main/java/com/team01/hrbank/repository/binarycontentstorage/BinaryContentStorageImpl.java

Closes #43
---
- 메타 데이터 저장소 구현
- 로컬 파일 저장소 구현
---
- 바이너리 콘텐트 저장소 구현
- 실제 이미지 스토리지 구현

[양찬혁 | 0422] (파일관리) 바이너리 콘텐트 레포지토리 및 스토리지 생성 완료

---

.gitignore
src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeDto.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/exception/DuplicateDepartmentNameException.java
src/main/java/com/team01/hrbank/exception/DuplicateException.java
src/main/java/com/team01/hrbank/repository/DepartmentRepository.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/DepartmentServiceImpl.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #26 
---
- contoller 구현
- 전역 예외 처리 수정
- .gitIgnore 수정
---
- save 컨트롤러 구현
- 중복 예외 처리 수정
- gitIgnore에 리소스 추가

[한성태 | 0423] Feature/26 직원 등록 컨트롤러 구현

---

src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/DepartmentService.java
src/main/java/com/team01/hrbank/service/impl/DepartmentServiceImpl.java

Closes #63 
---
부서 삭제 시 소속 직원 존재 여부를 확인하고, 조건을 만족할 경우 삭제 처리하는 서비스 로직을 구현
소속 직원이 존재하면 삭제를 차단하고, 존재하지 않을 경우 해당 부서를 삭제
---
- 소속 직원 존재 여부 확인 로직 작성
- employeeRepository.existsByDepartmentId(Long departmentId) 활용
- 소속 직원이 있을 경우 예외 발생 (IllegalStateException 또는 팀 공통 예외 활용)
- 부서 ID로 조회 후 삭제 처리 (repository.findById() → delete())

[안재관 | 0423 ]Feature/63 부서 삭제 로직 및 소속 직원 존재 여부 검사

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java

Closes #58 
---
- 직원 목록 조회 컨트롤러 구현
---
- 커서 페이지네이션을 적용한 컨트롤러 구현

[한성태 | 0423] Feature/58 직원 조회 contoller 구현

---

src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #71
---
- service 및 예외 처리 구현
---
- findById 구현

[한성태 | 0423] Feature/71 유저 상세 조회 service 구현

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/mapper/EmployeeMapper.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #72 
---
- 직원 상세 조회 api 구현
- Enun 타입 컨버터 구현
---
- 상세 조회 N + 1 문제 해결
- Enum타입인 직원 상태 converter 구현
- 상세조회 contoller 메서드 구현

[한성태 | 0423] Feature/72 직원 상세 조회 controller 구현

---

src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #80 
---
- 직원 삭제 service 구현
- Employee 클래스 수정
---
- 직원을 찾을 수 없을 때 예외 처리 구현
- 직원 삭제 시 이미지도 같이 삭제되도록 엔티티에 CascadeType.REMOVE 추가
- 직원 삭제 서비스 로직 구현

[한성태 | 0423] Feature/80 직원 삭제 service 구현

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java

Closes #81
---
- 직원 삭제 api 구현
- 테스트 진행 완료
---
- 직원 삭제 api 구현
- 직원 삭제 시 연관된 binary_contents 삭제되도록 구현
- 직원 삭제 성공 시 204 상태 반환하도록 구현

[한성태 | 0423] Feature/81 직원 삭제 관련 API 구현 및 테스트 완료

---

src/main/java/com/team01/hrbank/constraint/EmployeeStatus.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeUpdateRequest.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #85 
---
- 직원 수정 요청 객체 구현
- service 로직 구현
---
- EmployeeUpdateRequest 구현
- EmployeeStatus에 스트링을 EmployeeStatus 객체로 바꾸는 메서드 추가
- service 단에 update 메서드 추가
- Employee 엔티티에 update 메서드 추가

[한성태 | 0424] Feature/85 직원 수정 service 로직 구현

---

.gitignore
src/main/java/com/team01/hrbank/converter/EmployeeStatusConverter.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeTrendDto.java
src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/enums/EmployeeStatus.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #98
---
- repository 메소드 구현
- service 메소드 구현
- dto 구현
---
- service에 직원수 추이 조회를 위한 getEmployeeTrend 메서드
- 직원 수 추이 조회를 위한 repositry 기능 추가
- 응답값을 위한 dto 객체 구현

[한성태 | 0424] Feature/98 직원 수 추이 조회 service 구현

---

.gitignore
build.gradle
src/main/java/com/team01/hrbank/config/AppConfig.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeDistributionDto.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #103 
---
- queryDsl 환경 구성
- 직원 분포 조회 service 구현
- 직원 분포 조회 repository 구현
---
- queryDsl 을 사용하기 위한 AppConfig 구현
- repository directory  추가(custom, impl)
- 직원 분포 조회를 위한 서비스 구현
- 직원 분포 조회를 위한 repo queryDsl을 이용해 구현

[한성태 | 0424] Feature/103 직원 분포 조회 service 구현 및 QeuryDsl 환경

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/enums/TimeUnit.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #104 
---
- 직원 분포 조회 api 구현
---
- 직원 분포 조회 contoller 메소드 구현
- 잘못된 요청에 대한 예외처리 구현

[한성태 | 0424] Feature/104 직원 분포 조회 api 구현 및 예외처리 추가 및 테스트 수행

---

src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java
src/main/java/com/team01/hrbank/service/EmployeeService.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #108
---
- 직원 수 조회 repository 기능 추가
- 직원 수 조회 service 기능 추가
- 예외 처리 추가
---
- queryDsl 을 이용한 repository 구현
- 직원 수 조회 비즈니스 로직 구현 및 400에러 예외 처리 구현

[한성태 : 0425] Feature/108 직원 수 조회 비즈니스 로직 및 repo 구현

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeQueryRepositoryImpl.java

Closes #109 
---
- 직원 수 조회 api 구현
- 직원 수 조회 테스트 진행
---
- 직원 수 조회에 대한 컨트롤러 메서드 추가
- 직원 수 조회에 postman을 활용한 테스트 진행

[한성태 | 0425] Feature/109 직원수 조회 api 구현 및 테스트 진행

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/dto/changelog/CursorPageResponseChangeLogDto.java
src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
src/main/java/com/team01/hrbank/mapper/ChangeLogMapper.java
src/main/java/com/team01/hrbank/repository/ChangeLogDetailRepository.java
src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/ChangeLogQueryRepositoryImpl.java
src/main/java/com/team01/hrbank/service/ChangeLogService.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #113 
---
- Service, Controller 구현
- Repository QueryDSL에 맞게 구현(custom, impl)
---
api/change-logs 작업 완료

[윤영로 | 0425] Feature/113 직원 정보 수정 이력 목록 조회

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/repository/impl/ChangeLogQueryRepositoryImpl.java
src/main/java/com/team01/hrbank/service/ChangeLogService.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #35 
---
- 이력 상세 조회 구현
- api/change-logs/{id}/diffs
---
- ChangeLogQueryRepositoryImpl -> gt, lt 오름차순 내림차순 수정 구현
- ChangeLogServiceImpl -> 상세이력 조회 Service 딴에서 DiffDto반환 구현

[윤영로 | 0425] (직원 정보 수정 이력 관리) 직원 정보 수정 이력 상세 조회 구현

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
src/main/java/com/team01/hrbank/repository/impl/DepartmentRepositoryImpl.java
src/main/java/com/team01/hrbank/service/ChangeLogService.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #91 
---
- 수정이력건수조회
---
- repository, service, controller 건수조회 메서드 업데이트

[윤영로 | 0425] Feature/91 수정 이력 건수 조회

---

src/main/java/com/team01/hrbank/dto/employee/CursorPageRequestEmployeeDto.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeCreateRequest.java
src/main/java/com/team01/hrbank/dto/employee/EmployeeUpdateRequest.java
src/main/java/com/team01/hrbank/enums/EmployeeStatus.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #122 
---
- customRepositoy reposiytory 상속 및 로직 수정
---
- 프론트와 연동하며 오류가 생겼던 부분들을 수정
- repsitory에 queryDsl 인터페이스를 상속
- 중복 로직 제거

[한성태 | 0425] Fixed/122 직원 관리 직원에 대한 repository 고도화

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #이슈번호
---
CursorUtil 있기 이전 코드로 되돌리기
---
Controller, ServiceImpl 수정

[윤영로 | 0426] Fix CursorUtil 삭제로 인한 수정

---

src/main/java/com/team01/hrbank/repository/impl/DepartmentRepositoryImpl.java

Closes #126 
---
- 부서 기능 관련 API 테스트를 진행합니다.
---
- 커서 기반 페이지 네이션 로직 수정 및 추가

Feat: 부서 관련 API 테스트 중 에러 해결코드 추가

---

src/main/java/com/team01/hrbank/repository/impl/DepartmentRepositoryImpl.java

Closes #126 
---
- 정렬 시, 내림차순 적용했을때 여전히 오름차순정렬로 되는 현상 수정
---
- 정렬 필드 설정에서 파라미터값 수정

Fix: 정렬 관련 버그 수정

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/repository/custom/EmployeeQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #129 
---
- 직원 관리 조회 시 조건 추가 및 수정
---
- 직원 조회 조건 샘플 프로젝트와 일치하도록 수정

[한성태 | 0426] Feature/129 조회 조건 설정 추가

---

src/main/java/com/team01/hrbank/controller/EmployeeController.java
src/main/java/com/team01/hrbank/repository/impl/EmployeeRepositoryImpl.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #132 
---
- 직원 조회 시 조회 조건 추가
---
- 직원 수 추이 조회 시 해당 달에 퇴사자가 있다면 감소
- 직원 수 조회 시 전체 조회 추가

[한성태 | 0427] (직원 관리) Fixed/132 직원 수 추이 조회, 직원 수 조회 조회 시 조건 추가

---

src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java

[양찬혁|0427] (최종수정) 

---

src/main/java/com/team01/hrbank/entity/ChangeLog.java

Closes #이슈번호
---
--- 체인지 로그 수정
--- 체인지 로그 수정

[양찬혁 | 0427] (수정) change logs 수정

---

src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java

Closes #이슈번호
---
-백업 서비스 건너뜀 오류 발생 수정
-백업 서비스 건너뜀 오류 발생 수정

[양찬혁|0427 (백업) 백업 서비스 수정

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
src/main/java/com/team01/hrbank/entity/Backup.java
src/main/java/com/team01/hrbank/entity/ChangeLog.java
src/main/java/com/team01/hrbank/entity/ChangeLogDetail.java
src/main/java/com/team01/hrbank/mapper/ChangeLogMapper.java
src/main/java/com/team01/hrbank/repository/ChangeLogDetailRepository.java
src/main/java/com/team01/hrbank/repository/ChangeLogRepository.java
src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
src/main/java/com/team01/hrbank/service/ChangeLogService.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #139 
---
- 부서 등록 API 구현
- 컨트롤러, 서비스, DTO 작성
---
- Department 엔티티 생성
- POST /departments API 구현
- 유효성 검사 로직 추가 (부서명 중복 금지)
- 단위 테스트 코드 작성

[윤영로 | 0427] Fix/139 change log 관련 파일 정리

---

src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
src/main/java/com/team01/hrbank/exception/BackupFailedException.java
src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java

Closes #999
---
-서비스 로직 수정
-서비스 로직 수정

[양찬혁|0427] (수정) 실패 시에 상태 안 뜨는 오류  수정

---

src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java

Closes #이슈번호
---
-에러발생 주석처리
---
-에러발생 주석처리

[양찬혁|0427] (백업수정)에러발생 주석처리

---

src/main/java/com/team01/hrbank/repository/BackupRepository.java
src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java

Closes #이슈번호
---
-백업 서비스 로직 추가
-백업 서비스 로직 추가

[양찬혁|0427] (백업수정)서비스 로직 추가

---

src/main/java/com/team01/hrbank/entity/Backup.java
src/main/java/com/team01/hrbank/exception/BackupFailedException.java
src/main/java/com/team01/hrbank/repository/BackupRepository.java
src/main/java/com/team01/hrbank/repository/BinaryContentRepository.java
src/main/java/com/team01/hrbank/repository/impl/BackupRepositoryImpl.java
src/main/java/com/team01/hrbank/service/BackupService.java
src/main/java/com/team01/hrbank/service/BinaryContentService.java
src/main/java/com/team01/hrbank/service/impl/BackupServiceImpl.java
src/main/java/com/team01/hrbank/storage/BinaryContentStorage.java
src/main/java/com/team01/hrbank/storage/BinaryContentStorageImpl.java
src/main/java/com/team01/hrbank/storage/CsvBackupStorage.java
src/main/java/com/team01/hrbank/storage/CsvBackupStorageImpl.java

Closes #
---
- 주석 제거
- 익셉션 올바르게 교체
- 주석 제거
- 익셉션 올바르게 교체

[양찬혁|0248] (수정) 바이너리, 백업 최종 수정 완료

---

src/main/java/com/team01/hrbank/controller/DepartmentController.java
src/main/java/com/team01/hrbank/controller/advice/GlobalExceptionHandler.java
src/main/java/com/team01/hrbank/dto/department/DepartmentDto.java
src/main/java/com/team01/hrbank/repository/impl/DepartmentRepositoryImpl.java

Closes #이슈번호
---
- 주석 처리 및 코드 내 오타 수정
---

[안재관 | 0428] Fix: 주석 처리 등 일관성 유지

---

src/main/java/com/team01/hrbank/controller/ChangeLogController.java
src/main/java/com/team01/hrbank/dto/changelog/DiffDto.java
src/main/java/com/team01/hrbank/entity/ChangeLog.java
src/main/java/com/team01/hrbank/repository/custom/ChangeLogQueryRepository.java
src/main/java/com/team01/hrbank/repository/impl/ChangeLogRepositoryImpl.java
src/main/java/com/team01/hrbank/service/ChangeLogService.java
src/main/java/com/team01/hrbank/service/impl/ChangeLogServiceImpl.java

Closes #148 
---
- 마지막 수정
---
- 주석정리

[윤영로 | 0428] Fix ChangeLog관련 파일 수정

---

src/main/java/com/team01/hrbank/entity/Employee.java
src/main/java/com/team01/hrbank/repository/EmployeeRepository.java
src/main/java/com/team01/hrbank/service/impl/EmployeeServiceImpl.java

Closes #이슈번호
---
- 사원 번호 부여 조건 변경
---

사원번호 부여시 조건 변경

---

.gitignore
build.gradle
src/main/resources/application.yml
src/main/resources/schema.sql

Closes #이슈번호
---
-스키마 변경
---
-스키마 변경

[양찬혁 |0428] (수정) 최종수정
